table D_turnos
	lineageTag: 5de30bff-5266-4f0e-98af-9ec83e3855bb

	column ANO
		dataType: int64
		formatString: 0
		lineageTag: de64e102-9181-41e1-bfdd-8412fe7ea16d
		summarizeBy: none
		sourceColumn: ANO

		annotation SummarizationSetBy = Automatic

	column MÊS
		dataType: string
		lineageTag: c1dcf6c2-62ca-4b1a-8ae0-2b1c497b9d7c
		summarizeBy: none
		sourceColumn: MÊS

		annotation SummarizationSetBy = Automatic

	column TURNO
		dataType: string
		lineageTag: 98a3790b-44e5-40ba-89cc-ec274eb9b70e
		summarizeBy: none
		sourceColumn: TURNO

		annotation SummarizationSetBy = Automatic

	column 'HORA INÍCIO'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 9758a887-4f10-4ffc-b295-f210a1c65aff
		summarizeBy: none
		sourceColumn: HORA INÍCIO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'HORA FIM'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 1f8114dc-ac8a-42f0-a0f0-247d75a1d54d
		summarizeBy: none
		sourceColumn: HORA FIM

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'TEMPO MOBILIZAÇÃO (min)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: afc605d5-a590-4171-ad31-9bc8ad0f17c3
		summarizeBy: none
		sourceColumn: TEMPO MOBILIZAÇÃO (min)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'TEMPO DESMOBILIZAÇÃO (min)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: ddc056d6-9a94-498c-a73d-0f1a08ca928c
		summarizeBy: none
		sourceColumn: TEMPO DESMOBILIZAÇÃO (min)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'TEMPO DESLOCAMENTO (min)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 22c2a7c2-5920-4e0c-ad86-36599a026364
		summarizeBy: none
		sourceColumn: TEMPO DESLOCAMENTO (min)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'TEMPO INTERVALO (min)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 21e13515-ca4f-4fe7-bda6-01acc1b935ee
		summarizeBy: none
		sourceColumn: TEMPO INTERVALO (min)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'TEMPO TOTAL PREVISTO'
		dataType: dateTime
		formatString: Long Time
		lineageTag: d9b84471-f6b3-4da1-b6c1-6e6c70b8038b
		summarizeBy: none
		sourceColumn: TEMPO TOTAL PREVISTO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'META DISPONIBILIDADE'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 160b8e95-1d3a-45f6-8830-fed8eee96fb1
		summarizeBy: none
		sourceColumn: META DISPONIBILIDADE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'META PRODUÇÃO'
		dataType: int64
		formatString: 0
		lineageTag: 58d7f8f4-1ae3-42d0-87c6-e2bab3da5f8b
		summarizeBy: none
		sourceColumn: META PRODUÇÃO

		annotation SummarizationSetBy = Automatic

	column 'META PRODUTIVIDADE (hh)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 67899686-4ad9-43fa-a21a-93b3eee24608
		summarizeBy: none
		sourceColumn: META PRODUTIVIDADE (hh)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Tempo total do turno'
		dataType: string
		lineageTag: 89cd60a4-62fb-4bc8-8133-5c788cd44910
		summarizeBy: none
		sourceColumn: Tempo total do turno

		annotation SummarizationSetBy = Automatic

	column 'Total de Horas'
		dataType: double
		lineageTag: f6869d97-f55c-4b76-b61e-35ee51f36dab
		summarizeBy: none
		sourceColumn: Total de Horas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Horas úteis'
		dataType: string
		lineageTag: f01efc7b-c1ff-4577-a925-d01b7e7a3f42
		summarizeBy: none
		sourceColumn: Horas úteis

		annotation SummarizationSetBy = Automatic

	column 'META DISPONIBILIDADE MIN'
		dataType: double
		formatString: 0
		lineageTag: c49818ca-6a69-4068-b085-950a4b8bd610
		summarizeBy: none
		sourceColumn: META DISPONIBILIDADE MIN

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'META PRODUTIVIDADE MIN'
		dataType: double
		formatString: 0
		lineageTag: 265bdbd3-7ba3-4184-b555-1ae2c049bfd5
		summarizeBy: none
		sourceColumn: META PRODUTIVIDADE MIN

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition D_turnos = m
		mode: import
		queryGroup: 'Tabelas Dimensão'
		source = ```
				let
				    // Horários pré-setados (mesmos valores do painel OPE: T1/T2/T3, meta 15)
				    Fonte = Table.FromRecords({
				        [ANO = 2026, MÊS = "JULHO", TURNO = "T1", #"HORA INÍCIO" = #time(7, 30, 0), #"HORA FIM" = #time(16, 30, 0), #"TEMPO MOBILIZAÇÃO (min)" = #time(0, 20, 0), #"TEMPO DESMOBILIZAÇÃO (min)" = #time(0, 20, 0), #"TEMPO DESLOCAMENTO (min)" = #time(1, 0, 0), #"TEMPO INTERVALO (min)" = #time(1, 30, 0), #"TEMPO TOTAL PREVISTO" = #time(9, 0, 0), #"META DISPONIBILIDADE" = #time(5, 50, 0), #"META PRODUÇÃO" = 15, #"META PRODUTIVIDADE (hh)" = #time(0, 23, 20)],
				        [ANO = 2026, MÊS = "JULHO", TURNO = "T2", #"HORA INÍCIO" = #time(14, 0, 0), #"HORA FIM" = #time(23, 0, 0), #"TEMPO MOBILIZAÇÃO (min)" = #time(0, 20, 0), #"TEMPO DESMOBILIZAÇÃO (min)" = #time(0, 20, 0), #"TEMPO DESLOCAMENTO (min)" = #time(1, 0, 0), #"TEMPO INTERVALO (min)" = #time(1, 30, 0), #"TEMPO TOTAL PREVISTO" = #time(9, 0, 0), #"META DISPONIBILIDADE" = #time(5, 50, 0), #"META PRODUÇÃO" = 15, #"META PRODUTIVIDADE (hh)" = #time(0, 23, 20)],
				        [ANO = 2026, MÊS = "JULHO", TURNO = "T3", #"HORA INÍCIO" = #time(22, 0, 0), #"HORA FIM" = #time(6, 0, 0), #"TEMPO MOBILIZAÇÃO (min)" = #time(0, 20, 0), #"TEMPO DESMOBILIZAÇÃO (min)" = #time(0, 20, 0), #"TEMPO DESLOCAMENTO (min)" = #time(1, 0, 0), #"TEMPO INTERVALO (min)" = #time(1, 30, 0), #"TEMPO TOTAL PREVISTO" = #time(8, 0, 0), #"META DISPONIBILIDADE" = #time(4, 50, 0), #"META PRODUÇÃO" = 15, #"META PRODUTIVIDADE (hh)" = #time(0, 19, 20)]
				    }),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte, {{"ANO", Int64.Type}, {"MÊS", type text}, {"TURNO", type text}, {"HORA INÍCIO", type time}, {"HORA FIM", type time}, {"TEMPO MOBILIZAÇÃO (min)", type time}, {"TEMPO DESMOBILIZAÇÃO (min)", type time}, {"TEMPO DESLOCAMENTO (min)", type time}, {"TEMPO INTERVALO (min)", type time}, {"TEMPO TOTAL PREVISTO", type time}, {"META DISPONIBILIDADE", type time}, {"META PRODUÇÃO", Int64.Type}, {"META PRODUTIVIDADE (hh)", type time}}),
				    #"Tempo total do turno" = Table.AddColumn(#"Tipo Alterado", "Tempo total do turno", each if [HORA INÍCIO] = null or [HORA FIM] = null then null else if [HORA FIM] >= [HORA INÍCIO] then [HORA FIM] - [HORA INÍCIO] else ([HORA FIM] - [HORA INÍCIO]) + #duration(1, 0, 0, 0)),
				    #"Total de Horas" = Table.AddColumn(#"Tempo total do turno", "Total de Horas", each Duration.TotalHours([Tempo total do turno]), type number),
				    #"Horas úteis" = Table.AddColumn(#"Total de Horas", "Horas úteis", each let H = (t) => if t = null then 0 else Duration.TotalHours(t - #time(0, 0, 0)) in if [Total de Horas] = null then null else [Total de Horas] - H([#"TEMPO MOBILIZAÇÃO (min)"]) - H([#"TEMPO DESMOBILIZAÇÃO (min)"]) - H([#"TEMPO DESLOCAMENTO (min)"]) - H([#"TEMPO INTERVALO (min)"])),
				    #"META DISPONIBILIDADE MIN" = Table.AddColumn(#"Horas úteis", "META DISPONIBILIDADE MIN", each Duration.TotalMinutes([#"META DISPONIBILIDADE"] - #time(0, 0, 0)), type number),
				    #"META PRODUTIVIDADE MIN" = Table.AddColumn(#"META DISPONIBILIDADE MIN", "META PRODUTIVIDADE MIN", each Duration.TotalMinutes([#"META PRODUTIVIDADE (hh)"] - #time(0, 0, 0)), type number)
				in
				    #"META PRODUTIVIDADE MIN"
				```

annotation PBI_ResultType = Table

annotation PBI_NavigationStepName = Navegação