table F_atendimentos
	lineageTag: b61843a5-55f3-43a7-ab7b-3ac8267398a9

	column NUMERO_PROTOCOLO
		dataType: string
		lineageTag: 175924b7-4263-4f51-bdb4-19bc627ff071
		summarizeBy: none
		sourceColumn: NUMERO_PROTOCOLO

		annotation SummarizationSetBy = Automatic

	column TOTAL_ATENDIMENTOS
		dataType: string
		lineageTag: ba42d60d-f586-4a14-b929-be7a37b89332
		summarizeBy: none
		sourceColumn: TOTAL_ATENDIMENTOS

		annotation SummarizationSetBy = Automatic

	column TOTAL_CONFIRMADOS
		dataType: string
		lineageTag: 2eb948a6-d209-4277-8349-e508e2e1a583
		summarizeBy: none
		sourceColumn: TOTAL_CONFIRMADOS

		annotation SummarizationSetBy = Automatic

	column TOTAL_DESCONFIRMADOS
		dataType: string
		lineageTag: a27bc953-36f2-4777-a269-806e4f9dcd5c
		summarizeBy: none
		sourceColumn: TOTAL_DESCONFIRMADOS

		annotation SummarizationSetBy = Automatic

	column DIST
		dataType: string
		lineageTag: 6cba835e-2f4d-48b2-a1d4-79d085675ab3
		summarizeBy: none
		sourceColumn: DIST

		annotation SummarizationSetBy = Automatic

	column ID_POSICAO_GEOGRAFICA_EQUIPE
		dataType: string
		lineageTag: 6000659f-1bd9-413c-a528-033a28852013
		summarizeBy: none
		sourceColumn: ID_POSICAO_GEOGRAFICA_EQUIPE

		annotation SummarizationSetBy = Automatic

	column ID_ATENDIMENTO_PS
		dataType: string
		lineageTag: 92516189-ed5b-4410-8323-a4343c977b61
		summarizeBy: none
		sourceColumn: ID_ATENDIMENTO_PS

		annotation SummarizationSetBy = Automatic

	column ID_POSICAO_GEOGRAFICA_PONTO
		dataType: string
		lineageTag: 664f30ab-34c4-4e2c-9c9f-9bdb04fd1b94
		summarizeBy: none
		sourceColumn: ID_POSICAO_GEOGRAFICA_PONTO

		annotation SummarizationSetBy = Automatic

	column LATITUDE_TOTAL_PONTO
		dataType: string
		lineageTag: 6ef1a184-2977-4ea6-9e09-6c86e66e8975
		summarizeBy: none
		sourceColumn: LATITUDE_TOTAL_PONTO

		annotation SummarizationSetBy = Automatic

	column LONGITUDE_TOTAL_PONTO
		dataType: string
		lineageTag: c0b3959e-5f9d-48ce-8e25-5f9402ca0fb1
		summarizeBy: none
		sourceColumn: LONGITUDE_TOTAL_PONTO

		annotation SummarizationSetBy = Automatic

	column LATITUDE_TOTAL_EQUIPE
		dataType: string
		lineageTag: 52e4c6fd-a834-42a6-9bef-d29a6e339552
		summarizeBy: none
		sourceColumn: LATITUDE_TOTAL_EQUIPE

		annotation SummarizationSetBy = Automatic

	column LONGITUDE_TOTAL_EQUIPE
		dataType: string
		lineageTag: a79b4354-e467-4cf8-a144-406b1d1e7853
		summarizeBy: none
		sourceColumn: LONGITUDE_TOTAL_EQUIPE

		annotation SummarizationSetBy = Automatic

	column NUMERO_LOCAL_INICIAL
		dataType: string
		lineageTag: 8b10854c-08ce-4fc0-97b7-5c402072f7af
		summarizeBy: none
		sourceColumn: NUMERO_LOCAL_INICIAL

		annotation SummarizationSetBy = Automatic

	column ID_PARQUE_SERVICO
		dataType: string
		lineageTag: 89f8a886-2662-4d7c-a418-41e94f2a61a3
		summarizeBy: none
		sourceColumn: ID_PARQUE_SERVICO

		annotation SummarizationSetBy = Automatic

	column ENDERECO_LIVRE
		dataType: string
		lineageTag: 0b5eec31-7b91-46d9-805b-8bb8862dfb0d
		summarizeBy: none
		sourceColumn: ENDERECO_LIVRE

		annotation SummarizationSetBy = Automatic

	column NOME_BAIRRO
		dataType: string
		lineageTag: 451e0e5a-f71f-478b-ba35-3dcb3b0fbe87
		summarizeBy: none
		sourceColumn: NOME_BAIRRO

		annotation SummarizationSetBy = Automatic

	column NOME_MUNICIPIO
		dataType: string
		lineageTag: 8c7531f8-2020-4c9d-9679-bc0b155c631a
		summarizeBy: none
		sourceColumn: NOME_MUNICIPIO

		annotation SummarizationSetBy = Automatic

	column DESC_TIPO_LOGRADOURO
		dataType: string
		lineageTag: 2f6bc79e-1cf7-470b-b3d7-c8d3c2620ba6
		summarizeBy: none
		sourceColumn: DESC_TIPO_LOGRADOURO

		annotation SummarizationSetBy = Automatic

	column NOME_LOGRADOURO
		dataType: string
		lineageTag: a155482e-42f4-4f18-baec-f599bac791b0
		summarizeBy: none
		sourceColumn: NOME_LOGRADOURO

		annotation SummarizationSetBy = Automatic

	column DESC_STATUS_ATENDIMENTO_PS
		dataType: string
		lineageTag: 023247d7-0ffc-4793-9c02-e1c5525076bd
		summarizeBy: none
		sourceColumn: DESC_STATUS_ATENDIMENTO_PS

		annotation SummarizationSetBy = Automatic

	column DESC_MOTIVO_ATENDIMENTO_PS
		dataType: string
		lineageTag: 4412f2ae-b278-4dde-88c8-0c3f4c1ec0de
		summarizeBy: none
		sourceColumn: DESC_MOTIVO_ATENDIMENTO_PS

		annotation SummarizationSetBy = Automatic

	column NOME_LOGRADOURO_COMPLETO
		dataType: string
		lineageTag: 87737543-74de-48ad-bba7-7483a055b9b4
		summarizeBy: none
		sourceColumn: NOME_LOGRADOURO_COMPLETO

		annotation SummarizationSetBy = Automatic

	column ID_PONTO_SERVICO
		dataType: string
		lineageTag: 435dabf9-edd4-4c9b-8e65-eb299e044fbb
		summarizeBy: none
		sourceColumn: ID_PONTO_SERVICO

		annotation SummarizationSetBy = Automatic

	column DESC_SOLUCAO_ATENDIMENTO_PS
		dataType: string
		lineageTag: d259e435-ac3e-48f6-9329-9645eae59bb5
		summarizeBy: none
		sourceColumn: DESC_SOLUCAO_ATENDIMENTO_PS

		annotation SummarizationSetBy = Automatic

	column DATA_HORA_INICIO_ATENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 2ad541b1-6b95-419d-bb66-dd8c8c516337
		summarizeBy: none
		sourceColumn: DATA_HORA_INICIO_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column DATA_HORA_CONCLUSAO_ATENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 49502c1a-057f-4306-af57-a94de6ec7a09
		summarizeBy: none
		sourceColumn: DATA_HORA_CONCLUSAO_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column DATA_INICIO_ATENDIMENTO
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7309cfe5-8f99-499e-9861-415b57529cd6
		summarizeBy: none
		sourceColumn: DATA_INICIO_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DATA_CONCLUSAO_ATENDIMENTO
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3503ca47-c47a-489e-b9ca-b3717eb4f7f5
		summarizeBy: none
		sourceColumn: DATA_CONCLUSAO_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HORA_INICIO
		dataType: dateTime
		formatString: Long Time
		lineageTag: 56c1b0e6-caa3-4fb0-b9f5-7c822996f93b
		summarizeBy: none
		sourceColumn: HORA_INICIO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HORA_CONCLUSAO
		dataType: dateTime
		formatString: Long Time
		lineageTag: 56e2fb89-ea70-40e2-ae1e-79255b839553
		summarizeBy: none
		sourceColumn: HORA_CONCLUSAO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column DATA_ATENDIMENTO
		dataType: dateTime
		formatString: Long Date
		lineageTag: 844e578c-8bc5-4158-a52e-859024c7a032
		summarizeBy: none
		sourceColumn: DATA_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ID_AUTENT_CONFIRMACAO
		dataType: string
		lineageTag: aa4805ad-f355-4b8f-8a7d-dc78b17e8535
		summarizeBy: none
		sourceColumn: ID_AUTENT_CONFIRMACAO

		annotation SummarizationSetBy = Automatic

	column ID_DOMINIO
		dataType: string
		lineageTag: 3118b74c-a567-4614-a616-5b007b1c4339
		summarizeBy: none
		sourceColumn: ID_DOMINIO

		annotation SummarizationSetBy = Automatic

	column DESC_DOMINIO
		dataType: string
		lineageTag: b9653b79-41f8-46b9-b3b4-8843e28d9744
		summarizeBy: none
		sourceColumn: DESC_DOMINIO

		annotation SummarizationSetBy = Automatic

	column OBS
		dataType: string
		lineageTag: b5baca94-ddff-43a4-9411-b75ba8912a0e
		summarizeBy: none
		sourceColumn: OBS

		annotation SummarizationSetBy = Automatic

	column DESC_PRIORIDADE_PONTO_OCORR
		dataType: string
		lineageTag: deeb7e96-0092-4d3d-8189-f640bd793906
		summarizeBy: none
		sourceColumn: DESC_PRIORIDADE_PONTO_OCORR

		annotation SummarizationSetBy = Automatic

	column DESC_EQUIPE
		dataType: string
		lineageTag: eb164963-eba1-48ec-b9a0-773152738aeb
		summarizeBy: none
		sourceColumn: DESC_EQUIPE

		annotation SummarizationSetBy = Automatic

	column EMPRESA_USUARIA_EQUIPE
		dataType: string
		lineageTag: 54e005b3-4084-4f98-85ee-b85b827a01dc
		summarizeBy: none
		sourceColumn: EMPRESA_USUARIA_EQUIPE

		annotation SummarizationSetBy = Automatic

	column NOME_REGIAO
		dataType: string
		lineageTag: 3b35a3c5-797d-4420-b06e-f58f914a10a5
		summarizeBy: none
		sourceColumn: NOME_REGIAO

		annotation SummarizationSetBy = Automatic

	column NOME_PARQUE_SERVICO
		dataType: string
		lineageTag: ced3e370-2491-4b53-8a04-0f00cb5c7b0f
		summarizeBy: none
		sourceColumn: NOME_PARQUE_SERVICO

		annotation SummarizationSetBy = Automatic

	column VEICULOS
		dataType: string
		lineageTag: ff04e6ed-1e33-4a1c-aa32-e81480e9f969
		summarizeBy: none
		sourceColumn: VEICULOS

		annotation SummarizationSetBy = Automatic

	column DESC_TIPO_OCORRENCIA
		dataType: string
		lineageTag: cf375ae8-6e61-4f66-ab55-5c7dbb2bd4d2
		summarizeBy: none
		sourceColumn: DESC_TIPO_OCORRENCIA

		annotation SummarizationSetBy = Automatic

	column NUMERO_IDENTIFICACAO
		dataType: string
		lineageTag: c75ebac8-e818-484b-b68c-5630d40badb9
		summarizeBy: none
		sourceColumn: NUMERO_IDENTIFICACAO

		annotation SummarizationSetBy = Automatic

	column ENDERECO
		dataType: string
		lineageTag: 3b7d2922-55ee-4b7c-aca8-3e1e128c1d96
		summarizeBy: none
		sourceColumn: ENDERECO

		annotation SummarizationSetBy = Automatic

	column DataOperacional
		dataType: dateTime
		formatString: Short Date
		lineageTag: e19ca8ae-1ebd-434d-938b-d1d77580d14a
		summarizeBy: none
		sourceColumn: DataOperacional

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EquipeNormalizada
		dataType: string
		lineageTag: afdb1795-916a-4f3f-9124-ae3f016605fb
		summarizeBy: none
		sourceColumn: EquipeNormalizada

		annotation SummarizationSetBy = Automatic

	column EhEquipeManutencao
		dataType: boolean
		lineageTag: c75220c4-9eed-4235-a295-f35dd66a1530
		summarizeBy: none
		sourceColumn: EhEquipeManutencao

		annotation SummarizationSetBy = Automatic

	column EhEquipeCampo
		dataType: boolean
		lineageTag: 93b10578-fc90-415c-955e-2c737f434f92
		summarizeBy: none
		sourceColumn: EhEquipeCampo

		annotation SummarizationSetBy = Automatic

	column EhOperacional
		dataType: boolean
		lineageTag: 1c7e66a6-1de9-42a1-9cb5-d13bd5715d00
		summarizeBy: none
		sourceColumn: EhOperacional

		annotation SummarizationSetBy = Automatic

	column EhImpossibilidade
		dataType: boolean
		lineageTag: 67e06ef7-d3fd-427b-8d49-146a1c5ca941
		summarizeBy: none
		sourceColumn: EhImpossibilidade

		annotation SummarizationSetBy = Automatic

	column DuracaoExecucaoMin
		dataType: double
		formatString: 0
		lineageTag: 2fb28b96-d5b8-47e6-8412-ede5304e05f4
		summarizeBy: none
		sourceColumn: DuracaoExecucaoMin

		annotation SummarizationSetBy = Automatic

	column Turno
		dataType: string
		lineageTag: 46bf3643-6a0e-49a6-bfd7-5fa50c8f35c9
		summarizeBy: none
		sourceColumn: Turno

		annotation SummarizationSetBy = Automatic

	column ChaveEquipeDiaTurno
		dataType: string
		lineageTag: 1f123aa0-31a4-4943-85ea-9d053031353d
		summarizeBy: none
		sourceColumn: ChaveEquipeDiaTurno

		annotation SummarizationSetBy = Automatic

	measure Realizados = CALCULATE( DISTINCTCOUNT(F_atendimentos[ID_ATENDIMENTO_PS]), F_atendimentos[EhEquipeManutencao] = TRUE(), F_atendimentos[EhOperacional] = TRUE() )
		formatString: 0
		lineageTag: 36c50176-2620-47fa-a489-69be71bc6473

	measure 'Equipe-dia' = COUNTROWS( CALCULATETABLE( SUMMARIZE( F_atendimentos, F_atendimentos[EquipeNormalizada], F_atendimentos[DataOperacional] ), F_atendimentos[EhEquipeManutencao] = TRUE(), F_atendimentos[EhOperacional] = TRUE() ) )
		formatString: 0
		lineageTag: 857992cc-1b3b-4f70-b0d2-d424576f3b32

	measure 'Meta Produção' = 15 * [Equipe-dia]
		formatString: 0
		lineageTag: fc4a5631-5e52-4909-8a4d-c083abaed383

	measure Impossibilidades = CALCULATE( [Realizados], F_atendimentos[EhImpossibilidade] = TRUE() )
		formatString: 0
		lineageTag: 800a571f-cb59-41ca-9307-fa9ec5a9d4f5

	measure Válidos = MAX( 0, [Realizados] - [Impossibilidades] )
		formatString: 0
		lineageTag: 2d922fd5-1f5a-4431-aee1-8c5df9f6c2ae

	measure 'Tempo Base Min' = SUMX( CALCULATETABLE( SUMMARIZE( F_atendimentos, F_atendimentos[ChaveEquipeDiaTurno], F_atendimentos[Turno] ), F_atendimentos[EhEquipeManutencao] = TRUE(), F_atendimentos[EhOperacional] = TRUE() ), MAXX( FILTER( D_turnos, D_turnos[TURNO] = F_atendimentos[Turno] ), D_turnos[META DISPONIBILIDADE MIN] ) )
		formatString: 0
		lineageTag: 968ea990-f606-4b7b-a97f-10d9d2832c3e

	measure 'Paradas Min' =
        VAR BaseTurnos =
            SUMMARIZE(
                CALCULATETABLE( F_atendimentos, F_atendimentos[EhEquipeManutencao] = TRUE(), F_atendimentos[EhOperacional] = TRUE() ),
                F_atendimentos[EquipeNormalizada],
                F_atendimentos[DataOperacional],
                F_atendimentos[Turno]
            )
        RETURN
            SUMX(
                BaseTurnos,
                VAR Eq = F_atendimentos[EquipeNormalizada]
                VAR Dt = F_atendimentos[DataOperacional]
                VAR Tn = F_atendimentos[Turno]
                VAR InicioTurno =
                    SWITCH(
                        Tn,
                        "T1", Dt + TIME(7, 30, 0),
                        "T2", Dt + TIME(14, 0, 0),
                        "T3", Dt + TIME(22, 0, 0) - 1,
                        BLANK()
                    )
                VAR FimTurno =
                    SWITCH(
                        Tn,
                        "T1", Dt + TIME(16, 30, 0),
                        "T2", Dt + TIME(23, 0, 0),
                        "T3", Dt + TIME(6, 0, 0),
                        BLANK()
                    )
                RETURN
                    CALCULATE(
                        SUM( F_paradas[Tempo de parada] ),
                        REMOVEFILTERS( F_atendimentos ),
                        TREATAS( { Eq }, F_paradas[EquipeNormalizada] ),
                        F_paradas[EhNaoProgramada] = TRUE(),
                        F_paradas[Início da parada] >= InicioTurno,
                        F_paradas[Fim da parada] <= FimTurno
                    )
            )
		formatString: 0
		lineageTag: f5159d7e-eb2f-4b60-b637-cd5d06086f1d

	measure 'Tempo Disponível Min' = MAX( 0, [Tempo Base Min] - [Paradas Min] )
		formatString: 0
		lineageTag: f2357eeb-9520-419b-9cef-225083a956e7

	measure 'Disponibilidade %' = MIN( 1, DIVIDE( [Tempo Disponível Min], [Tempo Base Min] ) )
		formatString: 0.0%
		lineageTag: 43dbf102-d25b-4733-8c4c-fcfcc85d386a

	measure 'Meta Tempo Min' = COALESCE( MAX( D_turnos[META PRODUTIVIDADE MIN] ), 23 )
		formatString: 0
		lineageTag: a00a6400-3a28-46ca-a696-073888bbe61d

	measure 'Tempo Necessário Min' = [Meta Tempo Min] * [Válidos]
		formatString: 0
		lineageTag: 5f3ebf1f-2984-42da-9d4f-863ced03eb91

	measure 'Performance %' = DIVIDE( [Realizados], [Meta Produção] )
		formatString: 0.0%
		lineageTag: 79030dcb-8a03-42b2-927f-2a6ef8301c93

	measure 'Performance (Tempo) %' = DIVIDE( [Tempo Necessário Min], [Tempo Disponível Min] )
		formatString: 0.0%
		lineageTag: 7bf9c600-e300-477d-bfdb-e7e505d2e6e5

	measure 'Qualidade %' = DIVIDE( [Válidos], [Realizados] )
		formatString: 0.0%
		lineageTag: 3be5b71a-4f6c-4421-a94d-171864637269

	measure 'OPE %' = [Disponibilidade %] * [Performance %] * [Qualidade %]
		formatString: 0.0%
		lineageTag: 4c210590-084f-4116-9c72-26b943762966

	measure 'Disponibilidade (Limitada) %' = IF([Disponibilidade %] > 1, 1, [Disponibilidade %])
		formatString: 0.0%
		lineageTag: 422c4550-20f4-4f49-af05-195de92a9c9e

	measure 'Performance (Limitada) %' = IF([Performance %] > 1, 1, [Performance %])
		formatString: 0.0%
		lineageTag: 49920faa-b9b5-4a32-9c7a-d23a628128c2

	measure 'Qualidade (Limitada) %' = IF([Qualidade %] > 1, 1, [Qualidade %])
		formatString: 0.0%
		lineageTag: 931b713a-0d26-4d21-9af7-2fc6f1967a07

	measure 'OPE (Limitado) %' = [Disponibilidade (Limitada) %] * [Performance (Limitada) %] * [Qualidade (Limitada) %]
		formatString: 0.0%
		lineageTag: d0ec7edf-23aa-4af7-9ecb-d767c5d0f3b3

	measure md_qualidade = DIVIDE( CALCULATE( COUNT('F_atendimentos'[ID_ATENDIMENTO_PS]), F_atendimentos[DESC_STATUS_ATENDIMENTO_PS] = "Atendido" ), COUNT(F_atendimentos[ID_ATENDIMENTO_PS]), 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bb9725ae-9cff-4f85-b27c-3c80ec51401b

	measure md_encontrado_normal = CALCULATE( COUNT('F_atendimentos'[ID_ATENDIMENTO_PS]), F_atendimentos[DESC_STATUS_ATENDIMENTO_PS] = "Encontrado Normal" )
		formatString: 0
		lineageTag: d3f6a91b-69e8-4aa8-b48e-95aae6ed7486

	measure md_atendido = CALCULATE( COUNT('F_atendimentos'[ID_ATENDIMENTO_PS]), F_atendimentos[DESC_STATUS_ATENDIMENTO_PS] = "Atendido" )
		formatString: 0
		lineageTag: f5efd219-b304-4951-b2c1-95f459119806

	measure md_impossibilidade = CALCULATE( COUNT('F_atendimentos'[ID_ATENDIMENTO_PS]), F_atendimentos[DESC_STATUS_ATENDIMENTO_PS] = "Impossibilidade" )
		formatString: 0
		lineageTag: a316cc88-554e-4f00-b796-501bf4d4a890

	measure md_meta_impossibilidade = 10
		formatString: 0
		lineageTag: 521709fc-dc54-4378-a4c5-cfec0ccd4ac5

	partition F_atendimentos = m
		mode: import
		queryGroup: 'Tabela Fato'
		source = ```
				let
				    // credenciais do usuario de consulta — decisao do projeto: manter inline
				    User = "consulta.webservice",
				    Pass = "@consult56324",
				    URL_Login = "https://engiecuritiba.exati.com.br/guia/command/engiecuritiba?CMD.COMMAND=Login&CMD_username=" & User & "&CMD_password=" & Pass & "&parser=json",
				    RelativeURL = "/guia/command/engiecuritiba/relatoriosHouer.json",
				    // janela de dados da consulta (ajustavel: DATA_INICIO)
				    Parametros = "{""OPCAO"":""4"",""PAGE"":0,""PAGE_SIZE"":0,""DATA_INICIO"":""01/06/2026""}",
				    // Busca: re-login e bypass de cache (IsRetry) por tentativa; ate 6 tentativas com espera (lock ATD-BUS-0012)
				    Busca = (tentativa) =>
				        let
				            Tenta = try
				                (
				                    let
				                        GetJsonLogin = Json.Document(Web.Contents(URL_Login, [IsRetry = true])),
				                        ToTableLogin = Record.ToTable(GetJsonLogin),
				                        ExpandToken = Table.ExpandRecordColumn(ToTableLogin, "Value", {"AUTH_TOKEN"}, {"AUTH_TOKEN"}),
				                        AuthToken = List.Last(Record.FieldValues(ExpandToken{0})),
				                        Conteudo = Web.Contents("https://engiecuritiba.exati.com.br", [RelativePath = RelativeURL, Query = [CMD_SCRIPT_PARAMETERS = Parametros, auth_token = AuthToken], IsRetry = true, Timeout = #duration(0, 0, 5, 0)]),
				                        Json = Json.Document(Conteudo),
				                        Raiz = if Record.HasFields(Json, "RAIZ") then Json[RAIZ] else error ("Resposta da API Exati sem RAIZ. Conteudo: " & Text.FromBinary(Json.FromValue(Json))),
				                        Pontos = if Record.HasFields(Raiz, "PONTOS_ATENDIDOS") then Raiz[PONTOS_ATENDIDOS] else error ("Resposta da API Exati sem PONTOS_ATENDIDOS. Conteudo: " & Text.FromBinary(Json.FromValue(Json))),
				                        Lista = Pontos[PONTO_ATENDIDO]
				                    in
				                        Lista
				                )
				        in
				            if Tenta[HasError] and tentativa < 6 then Function.InvokeAfter(() => @Busca(tentativa + 1), #duration(0, 0, 0, 20 * tentativa)) else Tenta,
				    Bruto = Busca(1),
				    Detalhe = if Bruto[HasError] then (try Text.From(Bruto[Error][Message]) otherwise "(sem detalhes)") else "",
				    PONTO_ATENDIDO = if Bruto[HasError] then error ("Falha na API Exati apos 6 tentativas. Detalhe: " & Detalhe) else Bruto[Value],
				    #"Convertido para Tabela" = Table.FromList(PONTO_ATENDIDO, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"NUMERO_PROTOCOLO", "TOTAL_ATENDIMENTOS", "TOTAL_CONFIRMADOS", "TOTAL_DESCONFIRMADOS", "DIST", "ID_POSICAO_GEOGRAFICA_EQUIPE", "ID_ATENDIMENTO_PS", "ID_POSICAO_GEOGRAFICA_PONTO", "LATITUDE_TOTAL_PONTO", "LONGITUDE_TOTAL_PONTO", "LATITUDE_TOTAL_EQUIPE", "LONGITUDE_TOTAL_EQUIPE", "NUMERO_LOCAL_INICIAL", "ID_PARQUE_SERVICO", "ENDERECO_LIVRE", "NOME_BAIRRO", "NOME_MUNICIPIO", "DESC_TIPO_LOGRADOURO", "NOME_LOGRADOURO", "DESC_STATUS_ATENDIMENTO_PS", "DESC_MOTIVO_ATENDIMENTO_PS", "NOME_LOGRADOURO_COMPLETO", "ID_PONTO_SERVICO", "DESC_SOLUCAO_ATENDIMENTO_PS", "DATA_HORA_INICIO_ATENDIMENTO", "DATA_HORA_CONCLUSAO_ATENDIMENTO", "DATA_INICIO_ATENDIMENTO", "DATA_CONCLUSAO_ATENDIMENTO", "HORA_INICIO", "HORA_CONCLUSAO", "DATA_ATENDIMENTO", "ID_AUTENT_CONFIRMACAO", "ID_DOMINIO", "DESC_DOMINIO", "OBS", "DESC_PRIORIDADE_PONTO_OCORR", "DESC_EQUIPE", "EMPRESA_USUARIA_EQUIPE", "NOME_REGIAO", "NOME_PARQUE_SERVICO", "VEICULOS", "DESC_TIPO_OCORRENCIA", "NUMERO_IDENTIFICACAO", "ENDERECO"}, {"NUMERO_PROTOCOLO", "TOTAL_ATENDIMENTOS", "TOTAL_CONFIRMADOS", "TOTAL_DESCONFIRMADOS", "DIST", "ID_POSICAO_GEOGRAFICA_EQUIPE", "ID_ATENDIMENTO_PS", "ID_POSICAO_GEOGRAFICA_PONTO", "LATITUDE_TOTAL_PONTO", "LONGITUDE_TOTAL_PONTO", "LATITUDE_TOTAL_EQUIPE", "LONGITUDE_TOTAL_EQUIPE", "NUMERO_LOCAL_INICIAL", "ID_PARQUE_SERVICO", "ENDERECO_LIVRE", "NOME_BAIRRO", "NOME_MUNICIPIO", "DESC_TIPO_LOGRADOURO", "NOME_LOGRADOURO", "DESC_STATUS_ATENDIMENTO_PS", "DESC_MOTIVO_ATENDIMENTO_PS", "NOME_LOGRADOURO_COMPLETO", "ID_PONTO_SERVICO", "DESC_SOLUCAO_ATENDIMENTO_PS", "DATA_HORA_INICIO_ATENDIMENTO", "DATA_HORA_CONCLUSAO_ATENDIMENTO", "DATA_INICIO_ATENDIMENTO", "DATA_CONCLUSAO_ATENDIMENTO", "HORA_INICIO", "HORA_CONCLUSAO", "DATA_ATENDIMENTO", "ID_AUTENT_CONFIRMACAO", "ID_DOMINIO", "DESC_DOMINIO", "OBS", "DESC_PRIORIDADE_PONTO_OCORR", "DESC_EQUIPE", "EMPRESA_USUARIA_EQUIPE", "NOME_REGIAO", "NOME_PARQUE_SERVICO", "VEICULOS", "DESC_TIPO_OCORRENCIA", "NUMERO_IDENTIFICACAO", "ENDERECO"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Column1 Expandido", {{"DATA_HORA_INICIO_ATENDIMENTO", type datetime}, {"DATA_HORA_CONCLUSAO_ATENDIMENTO", type datetime}, {"DATA_INICIO_ATENDIMENTO", type date}, {"DATA_CONCLUSAO_ATENDIMENTO", type date}, {"HORA_INICIO", type time}, {"HORA_CONCLUSAO", type time}, {"DATA_ATENDIMENTO", type date}}),
				    #"Início Válido" = Table.SelectRows(#"Tipo Alterado", each [DATA_HORA_INICIO_ATENDIMENTO] <> null),
				    DataOperacional = Table.AddColumn(#"Início Válido", "DataOperacional", each if Time.From([DATA_HORA_INICIO_ATENDIMENTO]) <= #time(6, 30, 0) then Date.AddDays(Date.From([DATA_HORA_INICIO_ATENDIMENTO]), -1) else Date.From([DATA_HORA_INICIO_ATENDIMENTO]), type date),
				    EquipeNormalizada = Table.AddColumn(DataOperacional, "EquipeNormalizada", each let e = if [DESC_EQUIPE] = null then "" else [DESC_EQUIPE], p = Text.PositionOf(e, " | ") in Text.Trim(if p >= 0 then Text.Start(e, p) else e), type text),
				    EhEquipeCampo = Table.AddColumn(EquipeNormalizada, "EhEquipeCampo", each not Text.Contains([EquipeNormalizada], "CCO", Comparer.OrdinalIgnoreCase), type logical),
            EhEquipeManutencao = Table.AddColumn(EhEquipeCampo, "EhEquipeManutencao", each Text.StartsWith([EquipeNormalizada], "Man-", Comparer.OrdinalIgnoreCase), type logical),
				    MinutoDia = Table.AddColumn(EhEquipeManutencao, "MinutoDia", each Time.Hour([DATA_HORA_INICIO_ATENDIMENTO]) * 60 + Time.Minute([DATA_HORA_INICIO_ATENDIMENTO]), type number),
				    Turno = Table.AddColumn(MinutoDia, "Turno", each if [MinutoDia] <= 360 then "T3" else if [MinutoDia] <= 449 then "Fora" else if [MinutoDia] <= 990 then "T1" else if [MinutoDia] <= 1380 then "T2" else "T3", type text),
				    EhOperacional = Table.AddColumn(Turno, "EhOperacional", each [Turno] <> "Fora", type logical),
				    LimpaTexto = (t) => let u = Text.Upper(if t = null then "" else t) in Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(Text.Replace(u, "Á", "A"), "À", "A"), "Â", "A"), "Ã", "A"), "Ä", "A"), "É", "E"), "Ê", "E"), "È", "E"), "Í", "I"), "Ì", "I"), "Ó", "O"), "Ô", "O"), "Õ", "O"), "Ö", "O"), "Ú", "U"), "Ü", "U"), "Ç", "C"), "Ï", "I"), "Î", "I"), "Ù", "U"),
				    EhImpossibilidade = Table.AddColumn(EhOperacional, "EhImpossibilidade", each let st = LimpaTexto([DESC_STATUS_ATENDIMENTO_PS]) in st <> "ATENDIDO" and Text.Contains(st, "IMP"), type logical),
				    DuracaoExecucaoMin = Table.AddColumn(EhImpossibilidade, "DuracaoExecucaoMin", each if [DATA_HORA_CONCLUSAO_ATENDIMENTO] <> null and [DATA_HORA_CONCLUSAO_ATENDIMENTO] >= [DATA_HORA_INICIO_ATENDIMENTO] then Duration.TotalMinutes([DATA_HORA_CONCLUSAO_ATENDIMENTO] - [DATA_HORA_INICIO_ATENDIMENTO]) else null, type number),
				    ChaveEquipeDiaTurno = Table.AddColumn(DuracaoExecucaoMin, "ChaveEquipeDiaTurno", each [EquipeNormalizada] & "|" & Date.ToText([DataOperacional], "yyyy-MM-dd") & "|" & [Turno], type text),
				    SemAuxiliares = Table.RemoveColumns(ChaveEquipeDiaTurno, {"MinutoDia"})
				in
				    SemAuxiliares
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table
